language: ruby
ruby:
  - 2.6.3
cache: bundler

before_script:
  - bundle install

script:
  - bundle exec rspec

after_failure:
  - cd $TRAVIS_BUILD_DIR && ./travis/post_build_results

after_success:
  - cd $TRAVIS_BUILD_DIR && ./travis/post_build_results
