development: &base
  session_secret: xxx
  # database_url: "postgres://localhost/berg_development"
  # assets_server_link_url: "http://localhost:8080"
  # assets_server_read_url: "http://localhost:8080"
  # admin_url: "http://localhost:3000/admin"
  # canonical_domain: "http://localhost:3000"
  # precompiled_assets: false
  # precompiled_assets_host:
  # app_mailer_from_email: "hello@berg.dev"
  # admin_mailer_from_email: "admin@berg.dev"
  # bugsnag_api_key:
  # postmark_api_key:
  # basic_auth_user:
  # basic_auth_password:
  # attache_uploads_base_url: "http://icelab-site.attache.me"
  # attache_downloads_base_url: "http://icelab-site.attache.me"
  # attache_secret_key: "xxx"
  aws_access_key_id:
  aws_secret_access_key:
  aws_bucket: "icelab-site-production"
  aws_region: "ap-southeast-2"
  ga_tracking_id:
test:
  <<: *base
  database_url: "postgres://localhost/berg_test"
  postmark_api_key: "POSTMARK_API_TEST"
production:
  <<: *base
