---
registry:
  - namespace:
      - :features
      - :enroll_app
      - :aca_shop_market
      - :benefit_market_catalog
    features:
      - key: :catalog_2020
        is_enabled: true
        meta:
          label: Catalog 2020
          type: :string
          description: Products and configuration for 2020 SHOP Enrollment
          default: 2020 benefit market catalog
          is_required: false
          is_visible: true
        settings:
          - key: :employee_count_max
            item: 50
            meta:
              label: Maximum employee count
              description: Employer eligibility limit for maximum number of employees 
              type: :integer
              default: 50
              is_required: true
              is_visible: true
          - key: :use_employer_attestation
            item: false
            meta:
              label: 'use employer attestation'
              description: 
              type: :boolean
              default: false
              is_required: true
              is_visible: true
          - key: :use_employer_sic
            item: false
            meta:
              label: 'use employer sic code'
              description: 
              type: :boolean
              default: false
              is_required: true
              is_visible: true    
          - key: :application_period
            item: Date.new(2019,1,1)..Date.new(2019,12,31)
            meta:
              label: 'application period'
              description: 
              type: :range
              default: Date.new(2019,1,1)..Date.new(2019,12,31)
              is_required: true
              is_visible: true
          - key: :application_interval_kind
            item: { monthly: "Monthly" }
            meta:
              label: 'application inverval kind'
              description:
              type: :enumerated_hash_array
              default: { monthly: "Monthly" }
              enum:  [
                        { monthly: "Monthly" },
                        { annual: "Annual" },
                        { annual_with_midyear_initial: "Annual with midyear initial groups" }
                      ]
              is_required: true
              is_visible: true
          - key: :probation_period_kinds
            item:  [
                      { paper_and_electronic: "Paper and Electronic" },
                      { paper_only: "Paper only" },
                      { electronic_only: "Electronic only" }
                    ]
            meta:
              label: 'probation period kinds'
              description: 
              type: :enumerated_hash_array
              default:  [
                          { paper_and_electronic: "Paper and Electronic" },
                          { paper_only: "Paper only" },
                          { electronic_only: "Electronic only" }
                        ]
              enum:   [
                          { first_of_month_before_15th: "First of month before 15th" },
                          { date_of_hire: "Date of hire" },
                          { first_of_month: "First of month following date of hire" },
                          { first_of_month_after_30_days: "First of month after 30 days following date of hire" },
                          { first_of_month_after_60_days: "First of month after 60 days following date of hire" }
                      ]
              is_required: true
              is_visible: true
          - key: :open_enrollment_length_months_max
            item: 2
            meta:
              label: 'open enrollment period length maxiumum'
              description: 
              type: :months
              default: 2
              is_required: true
              is_visible: true
          - key: :open_enrollment_length_days_min
            item: 5
            meta:
              label: 'open enrollment period length days minimum'
              description: 
              type: :days
              default: 5
              is_required: true
              is_visible: true
