name: Ticket Check

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check for ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: 'https://redmine.priv.dchbx.org/issues/%ticketNumber%'
          bodyRegex: 'RM-(?<ticketNumber>\d+)'
          bodyURLRegex: 'https?:\/\/redmine\.priv\.dchbx\.org\/issues\/(?<ticketNumber>\d+)'
